//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HoI4_Modding_Supporter.Database {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang_ja {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang_ja() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HoI4_Modding_Supporter.Database.Lang_ja", typeof(Lang_ja).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   初期 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _default {
            get {
                return ResourceManager.GetString("default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   通称名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string adj {
            get {
                return ResourceManager.GetString("adj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無政府主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string anarchism {
            get {
                return ResourceManager.GetString("anarchism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無政府共産主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string anarchist_communism {
            get {
                return ResourceManager.GetString("anarchist_communism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   反修正主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string anti_revisionism {
            get {
                return ResourceManager.GetString("anti_revisionism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中道主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string centrism {
            get {
                return ResourceManager.GetString("centrism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   共産主義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string communism {
            get {
                return ResourceManager.GetString("communism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   輸送船 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string convoy {
            get {
                return ResourceManager.GetString("convoy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国家タグ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ctag {
            get {
                return ResourceManager.GetString("ctag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カスタムイデオロギー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string custom_ideology {
            get {
                return ResourceManager.GetString("custom_ideology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   正式名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   民主主義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string democratic {
            get {
                return ResourceManager.GetString("democratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   独裁主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string despotism {
            get {
                return ResourceManager.GetString("despotism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ディレクトリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   選挙 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string election {
            get {
                return ResourceManager.GetString("election", resourceCulture);
            }
        }
        
        /// <summary>
        ///   陣営 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string faction {
            get {
                return ResourceManager.GetString("faction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファランジスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string falangism {
            get {
                return ResourceManager.GetString("falangism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファシズム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fascism {
            get {
                return ResourceManager.GetString("fascism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファシスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fascism_ideology {
            get {
                return ResourceManager.GetString("fascism_ideology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HoI4 Modding Supporter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string hms {
            get {
                return ResourceManager.GetString("hms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HoI4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string hoi4 {
            get {
                return ResourceManager.GetString("hoi4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レーニン主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string leninism {
            get {
                return ResourceManager.GetString("leninism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自由主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string liberalism {
            get {
                return ResourceManager.GetString("liberalism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マルクス主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string marxism {
            get {
                return ResourceManager.GetString("marxism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mod に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string mod {
            get {
                return ResourceManager.GetString("mod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   近代主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string moderatism {
            get {
                return ResourceManager.GetString("moderatism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国家指導者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string national_leader {
            get {
                return ResourceManager.GetString("national_leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   国家社会主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string nazism {
            get {
                return ResourceManager.GetString("nazism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   中道主義 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string neutrality {
            get {
                return ResourceManager.GetString("neutrality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   寡頭主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string oligarchism {
            get {
                return ResourceManager.GetString("oligarchism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   政党 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string party {
            get {
                return ResourceManager.GetString("party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   政治力 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string political_power {
            get {
                return ResourceManager.GetString("political_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   政党支持率 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string popularities {
            get {
                return ResourceManager.GetString("popularities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロヴィンス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string province {
            get {
                return ResourceManager.GetString("province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   レクシスト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string rexism {
            get {
                return ResourceManager.GetString("rexism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   与党 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ruling_party {
            get {
                return ResourceManager.GetString("ruling_party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   社会主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string socialism {
            get {
                return ResourceManager.GetString("socialism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   安定度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stability {
            get {
                return ResourceManager.GetString("stability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   スターリン主義者 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string stalinism {
            get {
                return ResourceManager.GetString("stalinism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ステート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   研究スロット に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string teach_slot {
            get {
                return ResourceManager.GetString("teach_slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string vew {
            get {
                return ResourceManager.GetString("vew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戦争協力度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string war_support {
            get {
                return ResourceManager.GetString("war_support", resourceCulture);
            }
        }
    }
}
